# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 13, 14, 9, 3, 990611, tzinfo=utc)),
        ),
    ]
