# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 21, 45, 46, 937000, tzinfo=utc), verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 10, 21, 45, 46, 937000, tzinfo=utc)),
        ),
    ]
