# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 17, 15, 35, 399204, tzinfo=utc)),
        ),
    ]
