# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image_master',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_image_path', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=512)),
                ('product_description', models.CharField(max_length=4000)),
                ('product_type', models.CharField(max_length=200)),
                ('product_color', models.CharField(max_length=200)),
                ('product_patern', models.CharField(max_length=200)),
                ('category_id', models.IntegerField()),
                ('subcateogry_category_id', models.IntegerField()),
                ('sale_flag', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='product_price_history',
            fields=[
                ('product_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.FloatField()),
                ('effective_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('updation_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product_master')),
            ],
        ),
        migrations.AddField(
            model_name='product_image_master',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product_master'),
        ),
    ]
